### ISSUE TITLE
Redis exists warning

### ISSUE THREAD

**Issue by sjovanelly** [Envek/graphql-anycable#14]
**Describe the bug**
Warning I noticed in logs after upgrading to Ruby 2.7.1

`Redis#exists(key)` will return an Integer in redis-rb 4.3. `exists?` returns a boolean, you should use it instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer =  true. To disable this message and keep the current (boolean) behaviour of 'exists' you can set `Redis.exists_returns_integer = false`, but this option will be removed in 5.0. (/Users/jovi/.rvm/gems/ruby-2.7.1/gems/graphql-anycable-0.4.0/lib/graphql/subscriptions/anycable_subscriptions.rb:74:in `block in execute_all')

**Versions**
ruby: 2.7.1
rails (or other framework): 6.0.3.2
graphql: latest
graphql-anycable: latest
anycable: latest

**Comment by Envek** [comment]
This is message from [redis client library](https://github.com/redis/redis-rb), not from Ruby.

They added `exists?` method only in the latest 4.2 release and immediately decided to change behavior of `exists` on next 4.3.0 release (see their [CHANGELOG for 4.2.0](https://github.com/redis/redis-rb/blob/master/CHANGELOG.md#420)) that leaves as in complicated state. We most probably need to support older versions, so now we need to refine or monkeypatch them. :disappointed:

**DO NOT opt-in to the new behavior until we release a fix for this!**

**Comment by Envek** [comment]
Or just require redis-rb 4.2+

Released in [0.4.1](https://github.com/anycable/graphql-anycable/releases/tag/v0.4.1)
