### ISSUE TITLE
Switch from fakeredis gem to real Redis in tests

### ISSUE THREAD

**Issue by Envek** [Envek/graphql-anycable#31]
To facilitate development of pull requests like this: https://github.com/anycable/graphql-anycable/pull/30

Tasks:
 - drop fakeredis
 - setup CI (see [this page](https://docs.github.com/en/actions/using-containerized-services/creating-redis-service-containers) in GitHub docs for example)

**Comment by arathunku** [comment]
:wave: another point for moving into this direction

```
WarningHandlers::Ruby::Warning: Redis#srem will always return an Integer in Redis 5.0.0. Use Redis#srem? instead.(called from: /usr/src/app/vendor/bundle/ruby/3.2.0/gems/graphql-anycable-1.1.5/lib/graphql/subscriptions/anycable_subscriptions.rb:196:in `block (2 levels) in delete_subscription')
```

I'm getting this deprecation warning, see: 4.8.0 release https://github.com/redis/redis-rb/blob/master/CHANGELOG.md#480 and I was going to add PR to switch to `srem?` but those methods are not even present on fakeredis. Only srem: https://github.com/guilleiguaran/fakeredis/blob/ba7e3b7423884d88b6d30b7ede37ebd489688243/lib/redis/connection/memory.rb#L576
