### ISSUE TITLE
Once GraphQL::AnyCable is added to the schema, inherited fields are lost

### ISSUE THREAD

**Issue by xxx** [Envek/graphql-anycable#42]
**Describe the bug**
I'm looking to set up graphql-anycable in our project, and am seeing an issue where inherited fields are missing in normal query results. This is not a subscription - I'm haven't even made it that far yet.

**Versions**
ruby: 3.2.2
rails (or other framework): 7.1.3
graphql: 2.2.5
graphql-anycable: commit d13d7881690380bc5f77da52f199b5c930c3e5f2 (the most recent gem release is quite out of date) 
anycable: 1.4.3

**GraphQL schema**

```ruby
class SubscriptionType < GraphQL::Schema::Object; end

class ApplicationSchema < GraphQL::Schema
  use GraphQL::AnyCable, broadcast: true
  query QueryType
  subscription SubscriptionType
end

class BaseObject < GraphQL::Schema::Object
  field :class_type, String, null: false

  def class_type
    object.class.name.camelize(:lower)
  end
end

class StrategyType < BaseObject
  field :id, ID, null: false
end

def QueryType < GraphQL::Schema::Object
  field :strategy, StrategyType

  def strategy
    {
      id: 2134,
      class_type: 'strategy'
    }
  end
end
```

```graphql
query {
  strategy {
    id
    classType
  }
}
```

**GraphQL query**

N/A

**Steps to reproduce**
Load any page that makes a graphql query.

**Expected behavior**
The queried fields are returned.

**Actual behavior**

Fields are missing.

without `use GraphQL::AnyCable` in the schema:
```json
{
  "classType": "strategy",
  "id": "2134",
  "__typename": "Strategy"
}
```

with it:
```json
{
  "id": "2134",
  "__typename": "Strategy"
}
```

`classType` is simply missing.

No other changes have been made. `SubscriptionType` exists, but is empty.

**Comment by Envek** [comment]
First of all, thanks for the report! This behavior is very surprising as this gem provides only subscription implementation and shouldn't affect query execution outside of subscriptions. Something very weird is happening somewhere.

**Comment by Envek** [comment]
@xxx, unfortunately I couldn't reproduce your issue (see https://github.com/anycable/graphql-anycable/commit/ccc93a12d74e8a60031c0e02af152ecf4fa6b974 and [job run 193]( https://github.com/anycable/graphql-anycable/actions/runs/7653189645/job/20854520875))

Please check what other GraphQL-Ruby plugins do you have.

**Comment by xxx** [comment]
I redid the integration this morning and... now I can't repeat the issue either. Not exactly sure what is up, but sorry for wasting your time on this.
