### ISSUE TITLE
-core subgem to release grpc dependencies

### ISSUE THREAD

**Issue by jjb** [Envek/graphql-anycable#43]
when using anycable over http, one doesn't need grpc 

https://docs.anycable.io/ruby/http_rpc?id=rpc-over-http

>NOTE: If you don't use AnyCable gRPC server in any environment, you can avoid installing gRPC dependencies by using the anycable-rails-core gem instead of anycable-rails.

this isn't possible with graphql-anycable though, because it has a dependency on anycable

so, i think we need a -core subgem

or maybe just modify this one so that grpc needs to be manually added

**Comment by jjb** [comment]
i have a version of my app working with this branch, with just the dependency name changed

https://github.com/anycable/graphql-anycable/compare/master...jjb:graphql-anycable:patch-1

**Comment by palkan** [comment]
We don't need a subgem here, this gem should depend on `anycable-core`. @Envek will you be able to craft a new release?

**Comment by Envek** [comment]
Yep, will do a new release. Going to bump a minor version at least, as it feels to be a bit breaking change.

**Comment by Envek** [comment]
Released in [1.2.0](https://github.com/anycable/graphql-anycable/releases/tag/v1.2.0)

**Comment by jjb** [comment]
Thanks! However I can't use it because my system still requires client-provided channel identifiers 😅 any chance you could bring that back, and take it out in 2.0?

**Comment by Envek** [comment]
> any chance you could bring that back, and take it out in 2.0?

Nope (too late)

Use [1.1.7](https://github.com/anycable/graphql-anycable/releases/tag/v1.1.7) instead.

**Comment by jjb** [comment]
wow, a version just for me! 😄 thanks!
