### ISSUE TITLE
Failed to run Rake task on Heroku

### ISSUE THREAD

**Issue by jpalumickas** [Envek/graphql-anycable#8]
Hey!

Thanks for this awesome gem!

When we try to run a Rake task on **Heroku** to cleanup old data, we have this error:
```
Redis::CommandError: ERR unknown command `object`, with args beginning with: `IDLETIME`, `graphql-channel:....`
```

On local env this command works fine 🙂

**Comment by Envek** [comment]
Well, [`OBJECT`](https://redis.io/commands/object) isn't available on Heroku:

> granted access to all commands within Redis **except … `OBJECT`**.

https://devcenter.heroku.com/articles/heroku-redis#connection-permissions

So, 2/3 of the rake task is not usable there. However, last 1/3 is usable so maybe it worth to add a way to skip first two steps :thinking:

**Comment by Envek** [comment]
Try this:
 1. Upgrade the gem to 0.3.2
 2. Set `GRAPHQL_ANYCABLE_USE_REDIS_OBJECT_ON_CLEANUP` environment variable to `false`
 3. Run the rake task: `rake graphql:anycable:clean`

Feel free to reopen this issue if it is not working after that.

**Comment by jpalumickas** [comment]
@Envek thanks! I think it's working now 🙂
